name: Tests CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8'
      - run: npm install
        working-directory: ./new server
      - run: npm install
        working-directory: ./new server/client
      - run: npm test
        working-directory: ./new server
