name: Tests CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
      working-directory: ./new server
    - name: Install modules
      run: yarn
      working-directory: ./new server/client
    - name: Install skbkontur
      run: yarn add @skbkontur/react-ui@4.10.0; yarn upgrade react react-dom
      working-directory: ./new server
    - name: Run tests
      run: yarn test:ci
      working-directory: ./new server
